### ISSUE TITLE
vendoring hebrew-special-numbers

### ISSUE THREAD

**Issue by ninjaaron** [chaimleib/hebrew-special-numbers#3]
We are planning to test your data package (and probably example code...) for use in the python-hebrew-numbers library: https://github.com/OriHoch/python-hebrew-numbers. (And then I would subsequently use that in my de-Romanization project at the Goethe University library. We're converting a bunch of Romanized catalog entries back to Hebrew. https://github.com/FID-Judaica)

I was just wondering if you have any thoughts about how we should distribute your work. Obviously the easiest thing would be to simply copy your data into our project, but then we risk missing out future bug fixes or whatever. We could also make it a git submodule, but I have to discuss that with the owner of python-hebrew-numbers.

Just wondering if you have any thoughts or wishes about distribution of your work. Thanks for special-hebrew-numbers!

**Comment by OriHoch** [comment]
hebrew-special-numbers should be installable via pip

if it's not published to pypi, you should be able to install directly from github, for example like this:

pip install --upgrade https://github.com/chaimleib/hebrew-special-numbers/archive/master.zip

**Comment by ninjaaron** [comment]
Just for any coming to this later, we went with submodules, since hebrew-special-numbers is more or less a data package.
